const STORAGE_KEY = 'mi-asistente.tasks.v1';
const MIGRATION_KEY = 'mi-asistente.local-migrated.v1';
const state = { tasks: loadTasks(), filter: 'all', search: '', tag: '', backend: false, chatMessages: [], chatPending: false };
const elements = { groups: document.querySelector('#task-groups'), tags: document.querySelector('#tag-filters'), summary: document.querySelector('#task-summary'), status: document.querySelector('#save-status'), dialog: document.querySelector('#task-dialog'), form: document.querySelector('#task-form'), chatForm: document.querySelector('#chat-form'), chatInput: document.querySelector('#chat-input'), chatSubmit: document.querySelector('#chat-submit'), chatMessages: document.querySelector('#chat-messages') };

document.addEventListener('DOMContentLoaded', async () => { document.querySelector('#current-date').textContent = new Intl.DateTimeFormat('es-MX', { weekday:'long', day:'numeric', month:'long' }).format(new Date()); bindEvents(); render(); if ('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js').catch(() => {}); await initializeApi(); });
function bindEvents() { document.querySelector('#new-task-button').addEventListener('click', () => openTaskDialog()); document.querySelector('#close-dialog').addEventListener('click', closeDialog); document.querySelector('#cancel-dialog').addEventListener('click', closeDialog); elements.form.addEventListener('submit', saveTask); elements.chatForm.addEventListener('submit', sendChatMessage); document.querySelector('#search-input').addEventListener('input', event => { state.search = event.target.value.toLowerCase(); render(); }); document.querySelectorAll('.filter-tab').forEach(button => button.addEventListener('click', () => { state.filter = button.dataset.filter; document.querySelectorAll('.filter-tab').forEach(tab => { tab.classList.toggle('is-active', tab === button); tab.setAttribute('aria-selected', tab === button); }); render(); })); elements.groups.addEventListener('click', handleTaskAction); elements.groups.addEventListener('change', event => { if (event.target.matches('.task-check')) toggleTask(event.target.dataset.id); }); }
function loadTasks() { try { return JSON.parse(localStorage.getItem(STORAGE_KEY)) || []; } catch { return []; } }
function persistLocal() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state.tasks)); }
function setStatus(message) { elements.status.textContent = message; }
async function api(path, options = {}) { const response = await fetch(path, { headers: { 'Content-Type': 'application/json' }, ...options }); if (!response.ok) throw new Error((await response.json().catch(() => ({}))).error || `API ${response.status}`); return response.status === 204 ? null : response.json(); }
async function initializeApi() { try { let tasks = await api('/api/tasks'); if (!tasks.length && state.tasks.length && !localStorage.getItem(MIGRATION_KEY)) { const migration = await api('/api/migrate/local-tasks', { method:'POST', body:JSON.stringify({ tasks:state.tasks }) }); tasks = migration.tasks; localStorage.setItem(MIGRATION_KEY, new Date().toISOString()); } state.tasks = tasks; state.backend = true; setStatus('Sincronizado con SQLite'); render(); } catch { state.backend = false; setStatus('Modo local'); } }
function uid() { return `${Date.now()}-${Math.random().toString(36).slice(2,8)}`; } function dateKey(date) { return date.toISOString().slice(0,10); } function todayKey() { return dateKey(new Date()); } function tomorrowKey() { const date = new Date(); date.setDate(date.getDate() + 1); return dateKey(date); } function normalizeTags(value) { return value.split(',').map(tag => tag.trim().replace(/^#?/,'#')).filter(Boolean); }
function visibleTasks() { return state.tasks.filter(task => { const haystack = `${task.title} ${task.description} ${task.tags.join(' ')}`.toLowerCase(); return (!state.search || haystack.includes(state.search)) && (!state.tag || task.tags.includes(state.tag)) && (state.filter === 'all' || (state.filter === 'completed' ? task.completed : !task.completed)); }); }
function render() { const pending = state.tasks.filter(task => !task.completed).length; elements.summary.textContent = pending ? `${pending} ${pending === 1 ? 'tarea pendiente' : 'tareas pendientes'}` : 'Sin tareas pendientes'; renderTags(); const groups = [{key:'today',title:'Hoy'},{key:'tomorrow',title:'Mañana'},{key:'upcoming',title:'Próximas'},{key:'completed',title:'Completadas'}]; const tasks = visibleTasks(); elements.groups.innerHTML = groups.map(group => { const groupTasks = tasks.filter(task => belongsTo(task, group.key)); return groupTasks.length ? `<section class="group"><div class="group-title"><span>${group.title}</span><span class="group-count">${groupTasks.length}</span></div>${groupTasks.map(taskTemplate).join('')}</section>` : ''; }).join('') || `<div class="empty-state"><div class="empty-icon">✦</div><p>No hay tareas que coincidan con tu vista.</p><button class="button button-primary" type="button" data-action="new">Crear una tarea</button></div>`; }
function renderTags() { const tags = [...new Set(state.tasks.flatMap(task => task.tags))].sort(); elements.tags.innerHTML = tags.map(tag => `<button class="tag-filter ${state.tag === tag ? 'is-active' : ''}" type="button" data-tag="${escapeHtml(tag)}">${escapeHtml(tag)}</button>`).join(''); elements.tags.querySelectorAll('[data-tag]').forEach(button => button.addEventListener('click', () => { state.tag = state.tag === button.dataset.tag ? '' : button.dataset.tag; render(); })); }
function belongsTo(task, group) { if (group === 'completed') return task.completed; if (task.completed) return false; if (group === 'today') return task.date === todayKey(); if (group === 'tomorrow') return task.date === tomorrowKey(); return !task.date || task.date > tomorrowKey(); }
function taskTemplate(task) { const date = task.date ? new Intl.DateTimeFormat('es-MX',{day:'numeric',month:'short'}).format(new Date(`${task.date}T12:00:00`)) : 'Sin fecha'; const time = task.time ? ` · ${task.time}` : ''; return `<article class="task-card ${task.completed ? 'is-complete' : ''}"><input class="task-check" type="checkbox" data-id="${task.id}" ${task.completed ? 'checked' : ''} aria-label="Marcar ${escapeHtml(task.title)} como completada"><div><h3 class="task-title">${escapeHtml(task.title)}</h3>${task.description ? `<p class="task-meta">${escapeHtml(task.description)}</p>` : ''}<div class="task-meta"><span>${date}${time}</span><span class="priority priority-${task.priority}">${priorityName(task.priority)}</span></div><div class="tags">${task.tags.map(tag => `<span class="tag">${escapeHtml(tag)}</span>`).join('')}</div></div><div class="task-actions"><button class="text-button" type="button" data-action="edit" data-id="${task.id}">Editar</button><button class="text-button" type="button" data-action="delete" data-id="${task.id}">Eliminar</button></div></article>`; }
function priorityName(priority) { return ({high:'Alta',medium:'Media',low:'Baja'})[priority] || 'Media'; } function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[character])); }
async function handleTaskAction(event) { const button = event.target.closest('[data-action]'); if (!button) return; if (button.dataset.action === 'new') return openTaskDialog(); if (button.dataset.action === 'edit') return openTaskDialog(state.tasks.find(task => String(task.id) === String(button.dataset.id))); if (button.dataset.action === 'delete' && confirm('¿Eliminar esta tarea?')) { try { if (state.backend) await api(`/api/tasks/${button.dataset.id}`, { method:'DELETE' }); state.tasks = state.tasks.filter(task => String(task.id) !== String(button.dataset.id)); persistLocal(); render(); setStatus(state.backend ? 'Sincronizado con SQLite' : 'Modo local'); } catch (error) { setStatus(`Error: ${error.message}`); } } }
async function toggleTask(id) { const task = state.tasks.find(item => String(item.id) === String(id)); if (!task) return; const completed = !task.completed; try { const updated = state.backend ? await api(`/api/tasks/${id}/complete`, { method:'PATCH', body:JSON.stringify({ completed }) }) : { ...task, completed, updatedAt:new Date().toISOString() }; Object.assign(task, updated); persistLocal(); render(); setStatus(state.backend ? 'Sincronizado con SQLite' : 'Modo local'); } catch (error) { setStatus(`Error: ${error.message}`); render(); } }
function openTaskDialog(task = null) { elements.form.reset(); document.querySelector('#task-id').value = task?.id || ''; document.querySelector('#dialog-kicker').textContent = task ? 'Editar tarea' : 'Nueva tarea'; document.querySelector('#dialog-title').textContent = task ? 'Actualiza los detalles' : 'Añade algo importante'; if (task) { document.querySelector('#task-title').value = task.title; document.querySelector('#task-description').value = task.description; document.querySelector('#task-date').value = task.date; document.querySelector('#task-time').value = task.time; document.querySelector('#task-priority').value = task.priority; document.querySelector('#task-reminder').value = task.reminder; document.querySelector('#task-tags').value = task.tags.join(', '); } elements.dialog.showModal(); document.querySelector('#task-title').focus(); }
function closeDialog() { elements.dialog.close(); }
async function saveTask(event) { event.preventDefault(); const id = document.querySelector('#task-id').value; const now = new Date().toISOString(); const existing = state.tasks.find(task => String(task.id) === String(id)); const values = {title:document.querySelector('#task-title').value.trim(),description:document.querySelector('#task-description').value.trim(),date:document.querySelector('#task-date').value,time:document.querySelector('#task-time').value,priority:document.querySelector('#task-priority').value,reminder:document.querySelector('#task-reminder').value,tags:normalizeTags(document.querySelector('#task-tags').value),completed:existing?.completed || false,updatedAt:now}; try { const saved = state.backend ? await api(id ? `/api/tasks/${id}` : '/api/tasks', { method:id ? 'PUT' : 'POST', body:JSON.stringify(values) }) : { id:id || uid(), createdAt:existing?.createdAt || now, ...values }; if (existing) Object.assign(existing, saved); else state.tasks.push(saved); persistLocal(); closeDialog(); render(); setStatus(state.backend ? 'Sincronizado con SQLite' : 'Modo local'); } catch (error) { setStatus(`Error: ${error.message}`); } }
async function sendChatMessage(event) { event.preventDefault(); const message = elements.chatInput.value.trim(); if (!message || state.chatPending) return; state.chatMessages.push({ role:'user', content:message }); elements.chatInput.value = ''; state.chatPending = true; renderChat(); try { const result = await api('/api/chat', { method:'POST', body:JSON.stringify({ messages:state.chatMessages }) }); state.chatMessages.push({ role:'assistant', content:result.message }); } catch (error) { state.chatMessages.push({ role:'assistant', content:`No pude responder: ${error.message}`, error:true }); } finally { state.chatPending = false; renderChat(); elements.chatInput.focus(); } }
function renderChat() { const messages = state.chatMessages.map(message => `<div class="chat-message ${message.role === 'assistant' ? 'assistant' : ''} ${message.error ? 'error' : ''}">${escapeHtml(message.content)}</div>`).join(''); const loading = state.chatPending ? '<div class="chat-message assistant loading">Pensando...</div>' : ''; elements.chatMessages.innerHTML = !messages && !loading ? '<div class="assistant-empty" id="chat-empty"><div class="sparkle" aria-hidden="true">✦</div><p>Hola. Estoy listo para conversar contigo.</p></div>' : messages + loading; elements.chatMessages.scrollTop = elements.chatMessages.scrollHeight; elements.chatInput.disabled = state.chatPending; elements.chatSubmit.disabled = state.chatPending; }