const path = require('node:path');
const sqlite3 = require('sqlite3').verbose();
const time = require('./time');
const database = new sqlite3.Database(path.join(__dirname, 'database.sqlite'));
function run(sql, parameters = []) { return new Promise((resolve, reject) => database.run(sql, parameters, function onRun(error) { error ? reject(error) : resolve({ id: this.lastID, changes: this.changes }); })); }
function get(sql, parameters = []) { return new Promise((resolve, reject) => database.get(sql, parameters, (error, row) => error ? reject(error) : resolve(row))); }
function all(sql, parameters = []) { return new Promise((resolve, reject) => database.all(sql, parameters, (error, rows) => error ? reject(error) : resolve(rows))); }
async function columnExists(table, column) { return Boolean(await get(`SELECT 1 FROM pragma_table_info(?) WHERE name = ?`, [table, column])); }
async function addColumnIfMissing(table, definition) { const column = definition.split(' ')[0]; if (!(await columnExists(table, column))) await run(`ALTER TABLE ${table} ADD COLUMN ${definition}`); }
async function initDatabase() { await run('PRAGMA foreign_keys = ON'); await run(`CREATE TABLE IF NOT EXISTS tasks (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', date TEXT NOT NULL DEFAULT '', time TEXT NOT NULL DEFAULT '', priority TEXT NOT NULL DEFAULT 'medium', completed INTEGER NOT NULL DEFAULT 0, reminder TEXT NOT NULL DEFAULT 'none', type TEXT NOT NULL DEFAULT 'task', created_at TEXT NOT NULL, updated_at TEXT NOT NULL)`); await addColumnIfMissing('tasks', 'type TEXT NOT NULL DEFAULT \'task\''); await run(`CREATE TABLE IF NOT EXISTS tags (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE, type TEXT NOT NULL DEFAULT 'general')`); await run(`CREATE TABLE IF NOT EXISTS task_tags (task_id INTEGER NOT NULL, tag_id INTEGER NOT NULL, PRIMARY KEY (task_id, tag_id), FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE, FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE)`); await run(`CREATE TABLE IF NOT EXISTS people (id INTEGER PRIMARY KEY AUTOINCREMENT, full_name TEXT NOT NULL, nickname TEXT NOT NULL DEFAULT '', relationship TEXT NOT NULL DEFAULT '', phone TEXT NOT NULL DEFAULT '', email TEXT NOT NULL DEFAULT '', organization TEXT NOT NULL DEFAULT '', notes TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, updated_at TEXT NOT NULL)`); for (const definition of ['nickname TEXT NOT NULL DEFAULT \'\'', 'phone TEXT NOT NULL DEFAULT \'\'', 'email TEXT NOT NULL DEFAULT \'\'', 'organization TEXT NOT NULL DEFAULT \'\'']) await addColumnIfMissing('people', definition); await run(`CREATE TABLE IF NOT EXISTS projects (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, updated_at TEXT NOT NULL)`); await run(`CREATE TABLE IF NOT EXISTS memories (id INTEGER PRIMARY KEY AUTOINCREMENT, category TEXT NOT NULL, key TEXT NOT NULL, value TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)`); await run(`CREATE TABLE IF NOT EXISTS task_people (task_id INTEGER NOT NULL, person_id INTEGER NOT NULL, PRIMARY KEY (task_id, person_id), FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE, FOREIGN KEY (person_id) REFERENCES people(id) ON DELETE CASCADE)`); await run(`CREATE TABLE IF NOT EXISTS task_projects (task_id INTEGER PRIMARY KEY, project_id INTEGER NOT NULL, FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE, FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE)`); await run(`CREATE TABLE IF NOT EXISTS reminders (id INTEGER PRIMARY KEY AUTOINCREMENT, task_id INTEGER NOT NULL, date_time TEXT NOT NULL, sent INTEGER NOT NULL DEFAULT 0, type TEXT NOT NULL DEFAULT 'notification', created_at TEXT NOT NULL DEFAULT '', updated_at TEXT NOT NULL DEFAULT '', FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE)`); for (const definition of ["created_at TEXT NOT NULL DEFAULT ''", "updated_at TEXT NOT NULL DEFAULT ''"]) await addColumnIfMissing('reminders', definition); }
function normalizeTag(value) { return String(value).normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/^#?/, '').trim().replace(/\s+/g, '-').replace(/[^a-z0-9:_-]+/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, ''); }
function tagType(name) { return name.includes(':') ? name.slice(1, name.indexOf(':')) : 'general'; }
async function attachTags(taskId, tags = []) { await run('DELETE FROM task_tags WHERE task_id = ?', [taskId]); const normalizedTags = [...new Set(tags.map(normalizeTag).filter(Boolean))]; for (const normalized of normalizedTags) { const name = `#${normalized}`; await run('INSERT OR IGNORE INTO tags (name, type) VALUES (?, ?)', [name, tagType(name)]); const tag = await get('SELECT id FROM tags WHERE name = ?', [name]); await run('INSERT OR IGNORE INTO task_tags (task_id, tag_id) VALUES (?, ?)', [taskId, tag.id]); } }
async function taskTags(taskId) { return all('SELECT tags.name FROM tags JOIN task_tags ON task_tags.tag_id = tags.id WHERE task_tags.task_id = ? ORDER BY tags.name', [taskId]).then(rows => rows.map(row => row.name)); }
async function searchTags(text = '') { const pattern = `%${String(text).trim().toLowerCase()}%`; return all('SELECT name FROM tags WHERE lower(name) LIKE ? ORDER BY name LIMIT 50', [pattern]); }
async function formatTask(row) { return row ? { ...row, completed: Boolean(row.completed), tags: await taskTags(row.id), people: await getTaskPeople(row.id), reminders: await findReminders({ taskId: row.id }), createdAt: row.created_at, updatedAt: row.updated_at } : null; }
async function findTask(id) { return formatTask(await get('SELECT * FROM tasks WHERE id = ?', [id])); }
async function findTasks() { const rows = await all('SELECT * FROM tasks ORDER BY completed ASC, CASE WHEN date = "" THEN 1 ELSE 0 END, date ASC, time ASC, id DESC'); return Promise.all(rows.map(formatTask)); }
async function searchTasks(filters = {}) { const conditions = []; const parameters = []; if (filters.text) { conditions.push('(tasks.title LIKE ? OR tasks.description LIKE ?)'); const pattern = `%${filters.text}%`; parameters.push(pattern, pattern); } if (filters.date !== undefined) { conditions.push('tasks.date = ?'); parameters.push(filters.date); } if (filters.completed !== undefined) { conditions.push('tasks.completed = ?'); parameters.push(filters.completed ? 1 : 0); } if (filters.priority) { conditions.push('tasks.priority = ?'); parameters.push(filters.priority); } if (filters.tag) { conditions.push('EXISTS (SELECT 1 FROM task_tags JOIN tags ON tags.id = task_tags.tag_id WHERE task_tags.task_id = tasks.id AND tags.name = ?)'); parameters.push(filters.tag); } if (filters.personId !== undefined) { conditions.push('EXISTS (SELECT 1 FROM task_people WHERE task_people.task_id = tasks.id AND task_people.person_id = ?)'); parameters.push(filters.personId); } if (filters.projectId !== undefined) { conditions.push('EXISTS (SELECT 1 FROM task_projects WHERE task_projects.task_id = tasks.id AND task_projects.project_id = ?)'); parameters.push(filters.projectId); } const where = conditions.length ? `WHERE ${conditions.join(' AND ')}` : ''; const rows = await all(`SELECT tasks.* FROM tasks ${where} ORDER BY tasks.completed ASC, CASE WHEN tasks.date = "" THEN 1 ELSE 0 END, tasks.date ASC, tasks.time ASC, tasks.id DESC`, parameters); return Promise.all(rows.map(formatTask)); }
function normalizeTitle(title) { return String(title).trim().toLowerCase().replace(/\s+/g, ' '); }
async function findDuplicateTask(data) { const rows = await all('SELECT * FROM tasks WHERE completed = 0 AND date = ?', [data.date || '']); const normalizedTitle = normalizeTitle(data.title); const match = rows.find(row => normalizeTitle(row.title) === normalizedTitle && ((!data.time && !row.time) || (data.time && row.time && data.time === row.time))); return formatTask(match); }
async function replaceTaskPeople(taskId, personIds) { await run('DELETE FROM task_people WHERE task_id = ?', [taskId]); for (const personId of personIds || []) await run('INSERT OR IGNORE INTO task_people (task_id, person_id) VALUES (?, ?)', [taskId, personId]); }
async function replaceTaskProject(taskId, projectId) { await run('DELETE FROM task_projects WHERE task_id = ?', [taskId]); if (projectId !== undefined && projectId !== null) await run('INSERT INTO task_projects (task_id, project_id) VALUES (?, ?)', [taskId, projectId]); }
async function getTaskPeople(taskId) { return all('SELECT people.id, people.full_name AS fullName, people.nickname, people.relationship, people.phone, people.email, people.organization FROM people JOIN task_people ON task_people.person_id = people.id WHERE task_people.task_id = ? ORDER BY people.full_name', [taskId]); }
async function getTaskProject(taskId) { return get('SELECT projects.id, projects.name, projects.description FROM projects JOIN task_projects ON task_projects.project_id = projects.id WHERE task_projects.task_id = ?', [taskId]); }
async function createTask(data) { const now = new Date().toISOString(); const result = await run('INSERT INTO tasks (title, description, date, time, priority, completed, reminder, type, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)', [data.title, data.description || '', data.date || '', data.time || '', data.priority || 'medium', data.completed ? 1 : 0, data.reminder || 'none', data.type || 'task', now, now]); await attachTags(result.id, data.tags); if (data.personIds) await replaceTaskPeople(result.id, data.personIds); if (Object.prototype.hasOwnProperty.call(data, 'projectId')) await replaceTaskProject(result.id, data.projectId); return findTask(result.id); }
async function updateTask(id, data) { const now = new Date().toISOString(); const result = await run('UPDATE tasks SET title = ?, description = ?, date = ?, time = ?, priority = ?, completed = ?, reminder = ?, type = ?, updated_at = ? WHERE id = ?', [data.title, data.description || '', data.date || '', data.time || '', data.priority || 'medium', data.completed ? 1 : 0, data.reminder || 'none', data.type || 'task', now, id]); if (!result.changes) return null; await attachTags(id, data.tags); if (data.personIds) await replaceTaskPeople(id, data.personIds); if (Object.prototype.hasOwnProperty.call(data, 'projectId')) await replaceTaskProject(id, data.projectId); return findTask(id); }
async function updateTaskPartial(id, data) { const existing = await findTask(id); if (!existing) return null; const fields = ['title', 'description', 'date', 'time', 'priority', 'completed', 'reminder', 'type']; const updates = []; const parameters = []; for (const field of fields) { if (Object.prototype.hasOwnProperty.call(data, field)) { updates.push(`${field} = ?`); parameters.push(field === 'completed' ? (data[field] ? 1 : 0) : data[field]); } } if (updates.length) { updates.push('updated_at = ?'); parameters.push(new Date().toISOString(), id); await run(`UPDATE tasks SET ${updates.join(', ')} WHERE id = ?`, parameters); } if (Object.prototype.hasOwnProperty.call(data, 'tags')) await attachTags(id, [...existing.tags, ...data.tags]); if (Object.prototype.hasOwnProperty.call(data, 'personIds')) await replaceTaskPeople(id, data.personIds); if (Object.prototype.hasOwnProperty.call(data, 'projectId')) await replaceTaskProject(id, data.projectId); return findTask(id); }
async function deleteTask(id) { return run('DELETE FROM tasks WHERE id = ?', [id]); }
async function findPerson(id) { return get('SELECT id, full_name AS fullName, nickname, relationship, phone, email, organization, notes, created_at AS createdAt, updated_at AS updatedAt FROM people WHERE id = ?', [id]); }
async function searchPeople(filters = {}) { const conditions = []; const parameters = []; for (const [field, value] of Object.entries({ full_name: filters.name, nickname: filters.nickname, relationship: filters.relationship, organization: filters.organization, phone: filters.phone, email: filters.email })) if (value) { conditions.push(`people.${field} LIKE ?`); parameters.push(`%${value}%`); } const where = conditions.length ? `WHERE ${conditions.join(' AND ')}` : ''; return all(`SELECT id, full_name AS fullName, nickname, relationship, phone, email, organization, notes FROM people ${where} ORDER BY full_name`, parameters); }
function normalizePersonName(value) { return String(value).normalize('NFD').replace(/[\u0300-\u036f]/g, '').trim().toLowerCase().replace(/\s+/g, ' '); }
async function findPersonByNormalizedName(fullName) { const people = await all('SELECT id, full_name AS fullName, nickname, relationship, phone, email, organization, notes FROM people'); const normalized = normalizePersonName(fullName); return people.find(person => normalizePersonName(person.fullName) === normalized) || null; }
async function createPerson(data) { const now = new Date().toISOString(); const result = await run('INSERT INTO people (full_name, nickname, relationship, phone, email, organization, notes, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)', [data.fullName, data.nickname || '', data.relationship || '', data.phone || '', data.email || '', data.organization || '', data.notes || '', now, now]); return findPerson(result.id); }
async function updatePersonPartial(id, data) { if (!(await findPerson(id))) return null; const fields = { fullName: 'full_name', nickname: 'nickname', relationship: 'relationship', phone: 'phone', email: 'email', organization: 'organization', notes: 'notes' }; const updates = []; const parameters = []; for (const [key, column] of Object.entries(fields)) if (Object.prototype.hasOwnProperty.call(data, key)) { updates.push(`${column} = ?`); parameters.push(data[key]); } if (updates.length) { updates.push('updated_at = ?'); parameters.push(new Date().toISOString(), id); await run(`UPDATE people SET ${updates.join(', ')} WHERE id = ?`, parameters); } return findPerson(id); }
async function findProject(id) { return get('SELECT id, name, description, created_at AS createdAt, updated_at AS updatedAt FROM projects WHERE id = ?', [id]); }
async function searchProjects(text) { if (!text) return all('SELECT id, name, description FROM projects ORDER BY name'); const pattern = `%${text}%`; return all('SELECT id, name, description FROM projects WHERE name LIKE ? OR description LIKE ? ORDER BY name', [pattern, pattern]); }
async function createProject(data) { const now = new Date().toISOString(); const result = await run('INSERT INTO projects (name, description, created_at, updated_at) VALUES (?, ?, ?, ?)', [data.name, data.description || '', now, now]); return findProject(result.id); }
async function searchMemories(filters = {}) { const conditions = []; const parameters = []; if (filters.category) { conditions.push('category = ?'); parameters.push(filters.category); } if (filters.key) { conditions.push('key LIKE ?'); parameters.push(`%${filters.key}%`); } if (filters.text) { conditions.push('value LIKE ?'); parameters.push(`%${filters.text}%`); } const where = conditions.length ? `WHERE ${conditions.join(' AND ')}` : ''; return all(`SELECT id, category, key, value FROM memories ${where} ORDER BY updated_at DESC`, parameters); }
async function createMemory(data) { const now = new Date().toISOString(); const result = await run('INSERT INTO memories (category, key, value, created_at, updated_at) VALUES (?, ?, ?, ?, ?)', [data.category, data.key, data.value, now, now]); return get('SELECT id, category, key, value FROM memories WHERE id = ?', [result.id]); }
async function updateMemoryPartial(id, data) { const existing = await get('SELECT id FROM memories WHERE id = ?', [id]); if (!existing) return null; const updates = []; const parameters = []; for (const field of ['category', 'key', 'value']) if (Object.prototype.hasOwnProperty.call(data, field)) { updates.push(`${field} = ?`); parameters.push(data[field]); } if (updates.length) { updates.push('updated_at = ?'); parameters.push(new Date().toISOString(), id); await run(`UPDATE memories SET ${updates.join(', ')} WHERE id = ?`, parameters); } return get('SELECT id, category, key, value FROM memories WHERE id = ?', [id]); }
async function findTasksByPerson(personId) { return searchTasks({ personId }); }
async function formatReminder(row) { if (!row) return null; return { ...row, sent: Boolean(row.sent), dateTime: row.date_time, localDateTime: time.toLocalDateTime(new Date(row.date_time)), task: row.task_id ? { id: row.task_id, title: row.task_title, date: row.task_date, time: row.task_time, type: row.task_type } : null, createdAt: row.created_at, updatedAt: row.updated_at }; }
async function findReminder(id) { return formatReminder(await get('SELECT reminders.*, tasks.title AS task_title, tasks.date AS task_date, tasks.time AS task_time, tasks.type AS task_type FROM reminders JOIN tasks ON tasks.id = reminders.task_id WHERE reminders.id = ?', [id])); }
async function findReminders(filters = {}) { const conditions = []; const parameters = []; if (filters.taskId !== undefined) { conditions.push('reminders.task_id = ?'); parameters.push(filters.taskId); } if (filters.sent !== undefined) { conditions.push('reminders.sent = ?'); parameters.push(filters.sent ? 1 : 0); } const where = conditions.length ? `WHERE ${conditions.join(' AND ')}` : ''; const rows = await all(`SELECT reminders.*, tasks.title AS task_title, tasks.date AS task_date, tasks.time AS task_time, tasks.type AS task_type FROM reminders JOIN tasks ON tasks.id = reminders.task_id ${where} ORDER BY reminders.date_time ASC, reminders.id ASC`, parameters); const formatted = await Promise.all(rows.map(formatReminder)); return filters.date ? formatted.filter(reminder => reminder.localDateTime.slice(0, 10) === filters.date) : formatted; }
async function findDuplicateReminder(taskId, dateTime) { return findReminder((await get('SELECT id FROM reminders WHERE task_id = ? AND date_time = ? LIMIT 1', [taskId, dateTime]))?.id); }
async function ensureReminderUniqueness() { const duplicates = await all('SELECT task_id, date_time, MIN(id) AS keep_id FROM reminders GROUP BY task_id, date_time HAVING COUNT(*) > 1'); for (const duplicate of duplicates) await run('DELETE FROM reminders WHERE task_id = ? AND date_time = ? AND id <> ?', [duplicate.task_id, duplicate.date_time, duplicate.keep_id]); await run('CREATE UNIQUE INDEX IF NOT EXISTS reminders_task_datetime_unique ON reminders(task_id, date_time)'); }
async function createReminder(data) { const now = time.getNow().toISOString(); const result = await run('INSERT INTO reminders (task_id, date_time, sent, type, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)', [data.taskId, data.dateTime, data.sent ? 1 : 0, data.type || 'notification', now, now]); return findReminder(result.id); }
async function updateReminderPartial(id, data) { const existing = await findReminder(id); if (!existing) return null; const fields = []; const parameters = []; for (const [field, column] of [['dateTime', 'date_time'], ['sent', 'sent'], ['type', 'type']]) if (Object.prototype.hasOwnProperty.call(data, field)) { fields.push(`${column} = ?`); parameters.push(field === 'sent' ? (data[field] ? 1 : 0) : data[field]); } if (fields.length) { fields.push('updated_at = ?'); parameters.push(time.getNow().toISOString(), id); await run(`UPDATE reminders SET ${fields.join(', ')} WHERE id = ?`, parameters); } return findReminder(id); }
async function deleteReminder(id) { return run('DELETE FROM reminders WHERE id = ?', [id]); }
async function markReminderSent(id) { return updateReminderPartial(id, { sent: true }); }
module.exports = { all, get, run, initDatabase, ensureReminderUniqueness, findTask, findTasks, searchTasks, searchTags, findDuplicateTask, createTask, updateTask, updateTaskPartial, deleteTask, findPerson, searchPeople, findPersonByNormalizedName, createPerson, updatePersonPartial, findProject, searchProjects, createProject, searchMemories, createMemory, updateMemoryPartial, replaceTaskPeople, replaceTaskProject, getTaskPeople, getTaskProject, findTasksByPerson, findReminder, findReminders, findDuplicateReminder, createReminder, updateReminderPartial, deleteReminder, markReminderSent };