require('dotenv').config();
const path = require('node:path');
const express = require('express');
const database = require('./database');
const ai = require('./ai');
const app = express();
const port = Number(process.env.PORT) || 3000;
const publicRoot = path.join(__dirname, '..');
app.use(express.json({ limit: '1mb' }));
app.use(express.static(publicRoot, { dotfiles: 'deny' }));
function requiredText(value, field) { if (typeof value !== 'string' || !value.trim()) throw new Error(`${field} es obligatorio`); return value.trim(); }
function taskInput(body) { return { title: requiredText(body.title, 'title'), description: String(body.description || ''), date: String(body.date || ''), time: String(body.time || ''), priority: ['low', 'medium', 'high'].includes(body.priority) ? body.priority : 'medium', completed: Boolean(body.completed), reminder: String(body.reminder || 'none'), tags: Array.isArray(body.tags) ? body.tags : [] }; }
function asyncRoute(handler) { return (request, response) => Promise.resolve(handler(request, response)).catch(error => { console.error(error); response.status(error.statusCode || (error.message.includes('obligatorio') || error.message.includes('debe') || error.message.includes('Cada mensaje') ? 400 : 500)).json({ error: error.message }); }); }
function chatInput(body) { if (!body || typeof body !== 'object') throw new Error('El cuerpo de la solicitud debe ser JSON'); if (body.message !== undefined && (typeof body.message !== 'string' || !body.message.trim() || body.message.length > ai.MAX_MESSAGE_LENGTH)) throw new Error(`message debe ser texto de hasta ${ai.MAX_MESSAGE_LENGTH} caracteres`); const messages = body.messages || (body.message ? [{ role: 'user', content: body.message }] : []); return ai.validateMessages(messages); }
app.get('/api/tasks', asyncRoute(async (request, response) => response.json(await database.findTasks())));
app.get('/api/tasks/:id', asyncRoute(async (request, response) => { const task = await database.findTask(request.params.id); return task ? response.json(task) : response.status(404).json({ error: 'Tarea no encontrada' }); }));
app.post('/api/tasks', asyncRoute(async (request, response) => response.status(201).json(await database.createTask(taskInput(request.body)))));
app.put('/api/tasks/:id', asyncRoute(async (request, response) => { const task = await database.updateTask(request.params.id, taskInput(request.body)); return task ? response.json(task) : response.status(404).json({ error: 'Tarea no encontrada' }); }));
app.delete('/api/tasks/:id', asyncRoute(async (request, response) => { const result = await database.run('DELETE FROM tasks WHERE id = ?', [request.params.id]); return result.changes ? response.status(204).end() : response.status(404).json({ error: 'Tarea no encontrada' }); }));
app.patch('/api/tasks/:id/complete', asyncRoute(async (request, response) => { const task = await database.findTask(request.params.id); if (!task) return response.status(404).json({ error: 'Tarea no encontrada' }); return response.json(await database.updateTask(request.params.id, { ...task, completed: request.body.completed === undefined ? !task.completed : Boolean(request.body.completed) })); }));
app.post('/api/chat', asyncRoute(async (request, response) => response.json(await ai.chat(chatInput(request.body)))));
app.post('/api/migrate/local-tasks', asyncRoute(async (request, response) => { if (!Array.isArray(request.body.tasks)) return response.status(400).json({ error: 'tasks debe ser un arreglo' }); const migrated = []; for (const task of request.body.tasks) migrated.push(await database.createTask(taskInput(task))); response.status(201).json({ migrated: migrated.length, tasks: migrated }); }));
app.get('/api/tags', asyncRoute(async (request, response) => response.json(await database.all('SELECT id, name, type FROM tags ORDER BY name'))));
app.post('/api/tags', asyncRoute(async (request, response) => { const name = requiredText(request.body.name, 'name').replace(/^#?/, '#'); const type = name.includes(':') ? name.slice(1, name.indexOf(':')) : 'general'; await database.run('INSERT OR IGNORE INTO tags (name, type) VALUES (?, ?)', [name, type]); response.status(201).json(await database.get('SELECT id, name, type FROM tags WHERE name = ?', [name])); }));
const simpleEntities = { people: { columns:'full_name, relationship, notes', values: body => [requiredText(body.fullName, 'fullName'), String(body.relationship || ''), String(body.notes || '')] }, projects: { columns:'name, description', values: body => [requiredText(body.name, 'name'), String(body.description || '')] }, memories: { columns:'category, key, value', values: body => [requiredText(body.category, 'category'), requiredText(body.key, 'key'), requiredText(body.value, 'value')] } };
for (const [entity, definition] of Object.entries(simpleEntities)) { app.get(`/api/${entity}`, asyncRoute(async (request, response) => response.json(await database.all(`SELECT * FROM ${entity} ORDER BY id DESC`)))); app.post(`/api/${entity}`, asyncRoute(async (request, response) => { const now = new Date().toISOString(); const values = definition.values(request.body); const result = await database.run(`INSERT INTO ${entity} (${definition.columns}, created_at, updated_at) VALUES (${values.map(() => '?').join(', ')}, ?, ?)`, [...values, now, now]); response.status(201).json(await database.get(`SELECT * FROM ${entity} WHERE id = ?`, [result.id])); })); }
app.put('/api/people/:id', asyncRoute(async (request, response) => { const values = simpleEntities.people.values(request.body); const result = await database.run('UPDATE people SET full_name = ?, relationship = ?, notes = ?, updated_at = ? WHERE id = ?', [...values, new Date().toISOString(), request.params.id]); return result.changes ? response.json(await database.get('SELECT * FROM people WHERE id = ?', [request.params.id])) : response.status(404).json({ error: 'Persona no encontrada' }); }));
app.delete('/api/people/:id', asyncRoute(async (request, response) => { const result = await database.run('DELETE FROM people WHERE id = ?', [request.params.id]); return result.changes ? response.status(204).end() : response.status(404).json({ error: 'Persona no encontrada' }); }));
app.get(/^(?!\/api(?:\/|$)).*/, (request, response) => response.sendFile(path.join(publicRoot, 'index.html')));
database.initDatabase().then(() => app.listen(port, () => console.log(`Mi Asistente disponible en http://localhost:${port}`))).catch(error => { console.error('No se pudo inicializar SQLite', error); process.exitCode = 1; });