require('dotenv').config();
const path = require('node:path');
const express = require('express');
const database = require('./database');
const ai = require('./ai');
const advisor = require('./advisor');
const reminderEngine = require('./reminderEngine');
const toolRunner = require('./tools');
const time = require('./time');
const multer = require('multer');
const transcription = require('./transcription');
const app = express();
const port = Number(process.env.PORT) || 3000;
const publicRoot = path.join(__dirname, '..');
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: transcription.MAX_AUDIO_BYTES, files: 1 } });
app.use(express.json({ limit: '1mb' }));
app.use(express.static(publicRoot, { dotfiles: 'deny' }));
app.post('/api/transcribe', upload.single('audio'), asyncRoute(async (request, response) => { if (!request.file) return response.status(400).json({ error: 'Falta el archivo de audio' }); const result = await transcription.transcribe({ buffer: request.file.buffer, mimeType: request.file.mimetype, originalName: request.file.originalname }); return response.json(result); }));
function requiredText(value, field) { if (typeof value !== 'string' || !value.trim()) throw new Error(`${field} es obligatorio`); return value.trim(); }
function taskInput(body) { return { title: requiredText(body.title, 'title'), description: String(body.description || ''), date: String(body.date || ''), time: String(body.time || ''), priority: ['low', 'medium', 'high'].includes(body.priority) ? body.priority : 'medium', completed: Boolean(body.completed), reminder: String(body.reminder || 'none'), type: ['task', 'appointment', 'event'].includes(body.type) ? body.type : 'task', tags: Array.isArray(body.tags) ? body.tags : [] }; }
function asyncRoute(handler) { return (request, response) => Promise.resolve(handler(request, response)).catch(error => { console.error(error); response.status(error.statusCode || (error.message.includes('obligatorio') || error.message.includes('debe') || error.message.includes('Cada mensaje') ? 400 : 500)).json({ error: error.message }); }); }
function chatInput(body) { if (!body || typeof body !== 'object') throw new Error('El cuerpo de la solicitud debe ser JSON'); if (body.message !== undefined && (typeof body.message !== 'string' || !body.message.trim() || body.message.length > ai.MAX_MESSAGE_LENGTH)) throw new Error(`message debe ser texto de hasta ${ai.MAX_MESSAGE_LENGTH} caracteres`); const messages = body.messages || (body.message ? [{ role: 'user', content: body.message }] : []); return ai.validateMessages(messages); }
app.get('/api/tasks', asyncRoute(async (request, response) => response.json(await database.findTasks())));
app.get('/api/config', asyncRoute(async (request, response) => response.json({ timezone: time.APP_TIMEZONE, today: time.getToday(), now: time.toLocalDateTime() })));
app.get('/api/tasks/:id', asyncRoute(async (request, response) => { const task = await database.findTask(request.params.id); return task ? response.json(task) : response.status(404).json({ error: 'Tarea no encontrada' }); }));
app.post('/api/tasks', asyncRoute(async (request, response) => { const task = await database.createTask(taskInput(request.body)); await advisor.analyze(); return response.status(201).json(task); }));
app.put('/api/tasks/:id', asyncRoute(async (request, response) => { const task = await database.updateTask(request.params.id, taskInput(request.body)); if (!task) return response.status(404).json({ error: 'Tarea no encontrada' }); await advisor.analyze(); return response.json(task); }));
app.delete('/api/tasks/:id', asyncRoute(async (request, response) => { const result = await database.run('DELETE FROM tasks WHERE id = ?', [request.params.id]); if (!result.changes) return response.status(404).json({ error: 'Tarea no encontrada' }); await advisor.analyze(); return response.status(204).end(); }));
app.patch('/api/tasks/:id/complete', asyncRoute(async (request, response) => { const task = await database.findTask(request.params.id); if (!task) return response.status(404).json({ error: 'Tarea no encontrada' }); const updated = await database.updateTask(request.params.id, { ...task, completed: request.body.completed === undefined ? !task.completed : Boolean(request.body.completed) }); await advisor.analyze(); return response.json(updated); }));
app.get('/api/alerts', asyncRoute(async (request, response) => response.json(await advisor.analyze())));
app.post('/api/alerts/:id/dismiss', asyncRoute(async (request, response) => response.json(await advisor.dismiss(request.params.id))));
app.post('/api/chat', asyncRoute(async (request, response) => { const result = await ai.chat(chatInput(request.body)); await advisor.analyze(); return response.json(result); }));
app.get('/api/reminders', asyncRoute(async (request, response) => response.json(await database.findReminders())));
app.get('/api/reminders/due', asyncRoute(async (request, response) => response.json(await reminderEngine.getDueReminders())));
app.post('/api/reminders', asyncRoute(async (request, response) => { const result = request.body.advance ? await toolRunner.execute('crear_recordatorio_relativo', request.body) : await toolRunner.execute('crear_recordatorio', request.body); if (result.ok) return response.status(201).json(result.data); if (result.reason === 'duplicate') return response.json(result.data); return response.status(400).json(result); }));
app.put('/api/reminders/:id', asyncRoute(async (request, response) => { const result = await toolRunner.execute('editar_recordatorio', { ...request.body, id: Number(request.params.id) }); return result.ok ? response.json(result.data) : response.status(400).json(result); }));
app.delete('/api/reminders/:id', asyncRoute(async (request, response) => { const result = await toolRunner.execute('eliminar_recordatorio', { id: Number(request.params.id) }); return result.ok ? response.status(204).end() : response.status(404).json(result); }));
app.post('/api/reminders/:id/snooze', asyncRoute(async (request, response) => { const result = await toolRunner.execute('posponer_recordatorio', { id: Number(request.params.id), minutes: Number(request.body.minutes) }); return result.ok ? response.json(result.data) : response.status(400).json(result); }));
app.post('/api/reminders/:id/sent', asyncRoute(async (request, response) => { const result = await toolRunner.execute('editar_recordatorio', { id: Number(request.params.id), sent: true }); return result.ok ? response.json(result.data) : response.status(404).json(result); }));
app.post('/api/migrate/local-tasks', asyncRoute(async (request, response) => { if (!Array.isArray(request.body.tasks)) return response.status(400).json({ error: 'tasks debe ser un arreglo' }); const migrated = []; for (const task of request.body.tasks) migrated.push(await database.createTask(taskInput(task))); response.status(201).json({ migrated: migrated.length, tasks: migrated }); }));
app.get('/api/tags', asyncRoute(async (request, response) => response.json(await database.all('SELECT id, name, type FROM tags ORDER BY name'))));
app.post('/api/tags', asyncRoute(async (request, response) => { const name = requiredText(request.body.name, 'name').replace(/^#?/, '#'); const type = name.includes(':') ? name.slice(1, name.indexOf(':')) : 'general'; await database.run('INSERT OR IGNORE INTO tags (name, type) VALUES (?, ?)', [name, type]); response.status(201).json(await database.get('SELECT id, name, type FROM tags WHERE name = ?', [name])); }));
const simpleEntities = { people: { columns:'full_name, relationship, notes', values: body => [requiredText(body.fullName, 'fullName'), String(body.relationship || ''), String(body.notes || '')] }, projects: { columns:'name, description', values: body => [requiredText(body.name, 'name'), String(body.description || '')] }, memories: { columns:'category, key, value', values: body => [requiredText(body.category, 'category'), requiredText(body.key, 'key'), requiredText(body.value, 'value')] } };
for (const [entity, definition] of Object.entries(simpleEntities)) { app.get(`/api/${entity}`, asyncRoute(async (request, response) => response.json(await database.all(`SELECT * FROM ${entity} ORDER BY id DESC`)))); app.post(`/api/${entity}`, asyncRoute(async (request, response) => { const now = new Date().toISOString(); const values = definition.values(request.body); const result = await database.run(`INSERT INTO ${entity} (${definition.columns}, created_at, updated_at) VALUES (${values.map(() => '?').join(', ')}, ?, ?)`, [...values, now, now]); response.status(201).json(await database.get(`SELECT * FROM ${entity} WHERE id = ?`, [result.id])); })); }
app.get('/api/people/:id', asyncRoute(async (request, response) => { const person = await database.findPerson(request.params.id); if (!person) return response.status(404).json({ error: 'Persona no encontrada' }); const tasks = await database.searchTasks({ personId: Number(request.params.id) }); return response.json({ ...person, tasks }); }));
app.post('/api/people', asyncRoute(async (request, response) => { const data = { fullName: requiredText(request.body.fullName, 'fullName'), nickname: String(request.body.nickname || ''), relationship: String(request.body.relationship || ''), phone: String(request.body.phone || ''), email: String(request.body.email || ''), organization: String(request.body.organization || ''), notes: String(request.body.notes || '') }; const existing = await database.findPersonByNormalizedName(data.fullName); if (existing) return response.status(409).json({ error: 'La persona ya existe', person: existing }); const person = await database.createPerson(data); await advisor.analyze(); return response.status(201).json(person); }));
app.put('/api/people/:id', asyncRoute(async (request, response) => { const id = Number(request.params.id); if (!(await database.findPerson(id))) return response.status(404).json({ error: 'Persona no encontrada' }); const fields = { fullName: 'full_name', nickname: 'nickname', relationship: 'relationship', phone: 'phone', email: 'email', organization: 'organization', notes: 'notes' }; const updates = []; const values = []; for (const [key, column] of Object.entries(fields)) if (request.body[key] !== undefined) { updates.push(`${column} = ?`); values.push(String(request.body[key])); } if (!updates.length) return response.status(400).json({ error: 'No hay campos para actualizar' }); updates.push('updated_at = ?'); values.push(new Date().toISOString(), id); await database.run(`UPDATE people SET ${updates.join(', ')} WHERE id = ?`, values); await advisor.analyze(); return response.json(await database.findPerson(id)); }));
app.delete('/api/people/:id', asyncRoute(async (request, response) => { const id = Number(request.params.id); if (!(await database.findPerson(id))) return response.status(404).json({ error: 'Persona no encontrada' }); await database.run('DELETE FROM task_people WHERE person_id = ?', [id]); const result = await database.run('DELETE FROM people WHERE id = ?', [id]); if (!result.changes) return response.status(404).json({ error: 'Persona no encontrada' }); await advisor.analyze(); return response.status(204).end(); }));
app.get(/^(?!\/api(?:\/|$)).*/, (request, response) => response.sendFile(path.join(publicRoot, 'index.html')));
database.initDatabase().then(() => database.ensureReminderUniqueness()).then(() => app.listen(port, () => console.log(`Mi Asistente disponible en http://localhost:${port}`))).catch(error => { console.error('No se pudo inicializar SQLite', error); process.exitCode = 1; });