const database = require('./database');
const advisor = require('./advisor');
const time = require('./time');

const MAX_TITLE_LENGTH = 120;
const MAX_DESCRIPTION_LENGTH = 2000;
const MAX_TEXT_LENGTH = 200;
const MAX_TAGS = 20;
const MAX_TAG_LENGTH = 50;
const MAX_PERSON_FIELD_LENGTH = 200;
const MAX_PHONE_LENGTH = 40;
const MAX_EMAIL_LENGTH = 254;
const MAX_MEMORY_LENGTH = 1000;
const priorities = ['low', 'medium', 'high'];
const reminders = ['none', '15m', '1h', '1d'];
const datePattern = /^\d{4}-\d{2}-\d{2}$/;
const timePattern = /^(?:[01]\d|2[0-3]):[0-5]\d$/;
const taskTypes = ['task', 'appointment', 'event'];

const taskFields = {
  title: { type: 'string', description: 'Título de la tarea, máximo 120 caracteres' },
  description: { type: 'string', description: 'Descripción opcional, máximo 2000 caracteres' },
  date: { type: 'string', description: 'Fecha absoluta con formato YYYY-MM-DD' },
  time: { type: 'string', description: 'Hora con formato HH:MM, en 24 horas' },
  priority: { type: 'string', enum: priorities },
  tags: { type: 'array', items: { type: 'string' }, maxItems: MAX_TAGS },
  reminder: { type: 'string', enum: reminders },
  type: { type: 'string', enum: taskTypes },
  personIds: { type: 'array', items: { type: 'integer', minimum: 1 }, maxItems: 20 },
  projectId: { type: 'integer', minimum: 1 }
};

const tools = [
  { type: 'function', function: { name: 'crear_tarea', description: 'Crea una tarea nueva. Usa fechas y horas absolutas ya convertidas. No permitas duplicados salvo confirmación explícita.', parameters: { type: 'object', additionalProperties: false, properties: { ...taskFields, allowDuplicate: { type: 'boolean', description: 'Permite crear una tarea duplicada solo si el usuario lo confirmó explícitamente' } }, required: ['title'] } } },
  { type: 'function', function: { name: 'buscar_tareas', description: 'Busca tareas reales en SQLite con los filtros proporcionados. Usa personaId después de buscar la persona.', parameters: { type: 'object', additionalProperties: false, properties: { texto: { type: 'string', maxLength: MAX_TEXT_LENGTH }, fecha: { type: 'string', description: 'YYYY-MM-DD' }, completada: { type: 'boolean' }, etiqueta: { type: 'string', maxLength: MAX_TAG_LENGTH }, prioridad: { type: 'string', enum: priorities }, personaId: { type: 'integer', minimum: 1 } } } } },
  { type: 'function', function: { name: 'consultar_alertas', description: 'Analiza tareas y personas actuales y devuelve solo situaciones relevantes que requieren atencion.', parameters: { type: 'object', additionalProperties: false, properties: {} } } },
  { type: 'function', function: { name: 'crear_recordatorio', description: 'Programa un recordatorio real para una tarea usando fecha y hora local de la aplicación.', parameters: { type: 'object', additionalProperties: false, properties: { taskId: { type: 'integer', minimum: 1 }, dateTime: { type: 'string', description: 'Fecha y hora local con formato YYYY-MM-DDTHH:MM' }, type: { type: 'string', maxLength: 40 } }, required: ['taskId', 'dateTime'] } } },
  { type: 'function', function: { name: 'crear_recordatorio_relativo', description: 'Calcula en backend y programa un recordatorio 15m, 1h o 1d antes de una tarea.', parameters: { type: 'object', additionalProperties: false, properties: { taskId: { type: 'integer', minimum: 1 }, advance: { type: 'string', enum: ['15m', '1h', '1d'] }, type: { type: 'string', maxLength: 40 } }, required: ['taskId', 'advance'] } } },
  { type: 'function', function: { name: 'buscar_recordatorios', description: 'Busca recordatorios guardados y pendientes.', parameters: { type: 'object', additionalProperties: false, properties: { taskId: { type: 'integer', minimum: 1 }, pending: { type: 'boolean' }, date: { type: 'string', description: 'YYYY-MM-DD local' }, sent: { type: 'boolean' } } } } },
  { type: 'function', function: { name: 'editar_recordatorio', description: 'Edita parcialmente un recordatorio existente.', parameters: { type: 'object', additionalProperties: false, properties: { id: { type: 'integer', minimum: 1 }, dateTime: { type: 'string', description: 'Fecha y hora local con formato YYYY-MM-DDTHH:MM' }, sent: { type: 'boolean' }, type: { type: 'string', maxLength: 40 } }, required: ['id'] } } },
  { type: 'function', function: { name: 'eliminar_recordatorio', description: 'Elimina un recordatorio existente.', parameters: { type: 'object', additionalProperties: false, properties: { id: { type: 'integer', minimum: 1 } }, required: ['id'] } } },
  { type: 'function', function: { name: 'posponer_recordatorio', description: 'Pospone un recordatorio existente y lo deja pendiente.', parameters: { type: 'object', additionalProperties: false, properties: { id: { type: 'integer', minimum: 1 }, minutes: { type: 'integer', minimum: 1, maximum: 10080 } }, required: ['id', 'minutes'] } } },
  { type: 'function', function: { name: 'buscar_etiquetas', description: 'Busca etiquetas existentes para reutilizar una etiqueta canónica en lugar de crear una variante.', parameters: { type: 'object', additionalProperties: false, properties: { texto: { type: 'string', maxLength: MAX_TAG_LENGTH } } } } },
  { type: 'function', function: { name: 'editar_tarea', description: 'Edita únicamente los campos indicados de una tarea existente.', parameters: { type: 'object', additionalProperties: false, properties: { id: { type: 'integer', minimum: 1 }, ...taskFields }, required: ['id'] } } },
  { type: 'function', function: { name: 'completar_tarea', description: 'Marca una tarea existente como completada.', parameters: { type: 'object', additionalProperties: false, properties: { id: { type: 'integer', minimum: 1 } }, required: ['id'] } } },
  { type: 'function', function: { name: 'eliminar_tarea', description: 'Elimina una tarea existente por ID. Busca primero si el usuario no dio un ID claro o hay ambigüedad.', parameters: { type: 'object', additionalProperties: false, properties: { id: { type: 'integer', minimum: 1 } }, required: ['id'] } } },
  { type: 'function', function: { name: 'buscar_personas', description: 'Busca personas reales por nombre, apodo, relación, organización, teléfono o correo.', parameters: { type: 'object', additionalProperties: false, properties: { nombre: { type: 'string', maxLength: MAX_PERSON_FIELD_LENGTH }, apodo: { type: 'string', maxLength: MAX_PERSON_FIELD_LENGTH }, relacion: { type: 'string', maxLength: MAX_PERSON_FIELD_LENGTH }, organizacion: { type: 'string', maxLength: MAX_PERSON_FIELD_LENGTH }, telefono: { type: 'string', maxLength: MAX_PHONE_LENGTH }, correo: { type: 'string', maxLength: MAX_EMAIL_LENGTH } } } } },
  { type: 'function', function: { name: 'crear_persona', description: 'Crea una ficha de contacto solo cuando el usuario lo pide o confirma.', parameters: { type: 'object', additionalProperties: false, properties: { fullName: { type: 'string', maxLength: MAX_PERSON_FIELD_LENGTH }, nickname: { type: 'string', maxLength: MAX_PERSON_FIELD_LENGTH }, relationship: { type: 'string', maxLength: MAX_PERSON_FIELD_LENGTH }, phone: { type: 'string', maxLength: MAX_PHONE_LENGTH }, email: { type: 'string', maxLength: MAX_EMAIL_LENGTH }, organization: { type: 'string', maxLength: MAX_PERSON_FIELD_LENGTH }, notes: { type: 'string', maxLength: MAX_MEMORY_LENGTH } }, required: ['fullName'] } } },
  { type: 'function', function: { name: 'editar_persona', description: 'Actualiza únicamente los campos proporcionados de una persona por ID.', parameters: { type: 'object', additionalProperties: false, properties: { id: { type: 'integer', minimum: 1 }, fullName: { type: 'string', maxLength: MAX_PERSON_FIELD_LENGTH }, nickname: { type: 'string', maxLength: MAX_PERSON_FIELD_LENGTH }, relationship: { type: 'string', maxLength: MAX_PERSON_FIELD_LENGTH }, phone: { type: 'string', maxLength: MAX_PHONE_LENGTH }, email: { type: 'string', maxLength: MAX_EMAIL_LENGTH }, organization: { type: 'string', maxLength: MAX_PERSON_FIELD_LENGTH }, notes: { type: 'string', maxLength: MAX_MEMORY_LENGTH } }, required: ['id'] } } },
  { type: 'function', function: { name: 'buscar_proyectos', description: 'Busca proyectos reales por nombre o descripción.', parameters: { type: 'object', additionalProperties: false, properties: { texto: { type: 'string', maxLength: MAX_TEXT_LENGTH } } } } },
  { type: 'function', function: { name: 'crear_proyecto', description: 'Crea un proyecto básico.', parameters: { type: 'object', additionalProperties: false, properties: { name: { type: 'string', maxLength: MAX_PERSON_FIELD_LENGTH }, description: { type: 'string', maxLength: MAX_DESCRIPTION_LENGTH } }, required: ['name'] } } },
  { type: 'function', function: { name: 'buscar_memoria', description: 'Busca memoria persistente guardada explícitamente por el usuario.', parameters: { type: 'object', additionalProperties: false, properties: { category: { type: 'string', maxLength: MAX_TEXT_LENGTH }, key: { type: 'string', maxLength: MAX_TEXT_LENGTH }, texto: { type: 'string', maxLength: MAX_TEXT_LENGTH } } } } },
  { type: 'function', function: { name: 'guardar_memoria', description: 'Guarda una memoria estructurada solo tras petición o confirmación explícita.', parameters: { type: 'object', additionalProperties: false, properties: { category: { type: 'string', maxLength: MAX_TEXT_LENGTH }, key: { type: 'string', maxLength: MAX_TEXT_LENGTH }, value: { type: 'string', maxLength: MAX_MEMORY_LENGTH } }, required: ['category', 'key', 'value'] } } },
  { type: 'function', function: { name: 'editar_memoria', description: 'Actualiza parcialmente una memoria persistente por ID.', parameters: { type: 'object', additionalProperties: false, properties: { id: { type: 'integer', minimum: 1 }, category: { type: 'string', maxLength: MAX_TEXT_LENGTH }, key: { type: 'string', maxLength: MAX_TEXT_LENGTH }, value: { type: 'string', maxLength: MAX_MEMORY_LENGTH } }, required: ['id'] } } }
];

function invalid(message) { const error = new Error(message); error.publicMessage = 'Los datos de la herramienta no son válidos.'; throw error; }
function assertKeys(value, allowed) { for (const key of Object.keys(value || {})) if (!allowed.includes(key)) invalid('argumentos no válidos'); }
function stringValue(value, field, max, required = false) { if (value === undefined && !required) return undefined; if (typeof value !== 'string' || (required && !value.trim()) || value.length > max) invalid(`${field} no es válido`); return value.trim(); }
function validateDate(value, field = 'date') { if (value === undefined) return undefined; if (typeof value !== 'string' || !datePattern.test(value)) invalid(`${field} no es válida`); const date = new Date(`${value}T00:00:00Z`); if (Number.isNaN(date.getTime()) || date.toISOString().slice(0, 10) !== value) invalid(`${field} no es válida`); return value; }
function validateTime(value) { if (value === undefined) return undefined; if (typeof value !== 'string' || !timePattern.test(value)) invalid('time no es válida'); return value; }
function normalizeTag(value) { return value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/^#?/, '').trim().replace(/\s+/g, '-').replace(/[^a-z0-9:_-]+/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, ''); }
function validateTags(value) { if (value === undefined) return undefined; if (!Array.isArray(value) || value.length > MAX_TAGS) invalid('tags no es válido'); const normalizedTags = value.map(tag => normalizeTag(stringValue(tag, 'tag', MAX_TAG_LENGTH, true))).filter(Boolean); return [...new Set(normalizedTags.map(tag => `#${tag}`))].slice(0, MAX_TAGS); }
function validateIdList(value) { if (!Array.isArray(value) || value.length > 20 || value.some(item => !Number.isInteger(item) || item < 1)) invalid('lista de IDs no válida'); return [...new Set(value)]; }
function validateTaskFields(args, { titleRequired = false } = {}) { if (!args || typeof args !== 'object' || Array.isArray(args)) invalid('argumentos no válidos'); assertKeys(args, Object.keys(taskFields).concat(titleRequired ? [] : ['id'])); const result = {}; if (titleRequired || Object.prototype.hasOwnProperty.call(args, 'title')) result.title = stringValue(args.title, 'title', MAX_TITLE_LENGTH, titleRequired); if (Object.prototype.hasOwnProperty.call(args, 'description')) result.description = stringValue(args.description, 'description', MAX_DESCRIPTION_LENGTH); if (Object.prototype.hasOwnProperty.call(args, 'date')) result.date = validateDate(args.date); if (Object.prototype.hasOwnProperty.call(args, 'time')) result.time = validateTime(args.time); if (Object.prototype.hasOwnProperty.call(args, 'priority')) { if (!priorities.includes(args.priority)) invalid('priority no es válida'); result.priority = args.priority; } if (Object.prototype.hasOwnProperty.call(args, 'tags')) result.tags = validateTags(args.tags); if (Object.prototype.hasOwnProperty.call(args, 'reminder')) { if (!reminders.includes(args.reminder)) invalid('reminder no es válido'); result.reminder = args.reminder; } if (Object.prototype.hasOwnProperty.call(args, 'type')) { if (!taskTypes.includes(args.type)) invalid('type no es válido'); result.type = args.type; } if (Object.prototype.hasOwnProperty.call(args, 'personIds')) result.personIds = validateIdList(args.personIds); if (Object.prototype.hasOwnProperty.call(args, 'projectId')) result.projectId = validateId(args.projectId); return result; }
function validatePersonFields(args, { fullNameRequired = false } = {}) { const allowed = ['fullName', 'nickname', 'relationship', 'phone', 'email', 'organization', 'notes']; assertKeys(args, allowed.concat(fullNameRequired ? [] : ['id'])); const result = {}; for (const [field, max] of Object.entries({ fullName: MAX_PERSON_FIELD_LENGTH, nickname: MAX_PERSON_FIELD_LENGTH, relationship: MAX_PERSON_FIELD_LENGTH, phone: MAX_PHONE_LENGTH, email: MAX_EMAIL_LENGTH, organization: MAX_PERSON_FIELD_LENGTH, notes: MAX_MEMORY_LENGTH })) if (fullNameRequired && field === 'fullName' || Object.prototype.hasOwnProperty.call(args, field)) result[field] = stringValue(args[field], field, max, fullNameRequired && field === 'fullName'); return result; }
function validateMemoryFields(args, { required = false } = {}) { const allowed = ['category', 'key', 'value']; assertKeys(args, allowed.concat(required ? [] : ['id'])); const result = {}; for (const field of allowed) if (required || Object.prototype.hasOwnProperty.call(args, field)) result[field] = stringValue(args[field], field, field === 'value' ? MAX_MEMORY_LENGTH : MAX_TEXT_LENGTH, required); return result; }
function validateId(value) { if (!Number.isInteger(value) || value < 1) invalid('id no es válido'); return value; }
function parseReminderDateTime(value) { try { return time.parseLocalDateTime(value).toISOString(); } catch (error) { invalid(error.message); } }

async function execute(name, rawArguments) {
  let args;
  try { args = typeof rawArguments === 'string' ? JSON.parse(rawArguments) : rawArguments; } catch { invalid('JSON de argumentos no válido'); }
  try {
    if (name === 'crear_tarea') { if (!args || typeof args !== 'object' || Array.isArray(args)) invalid('argumentos no válidos'); assertKeys(args, [...Object.keys(taskFields), 'allowDuplicate']); const { allowDuplicate = false, ...taskArguments } = args; if (typeof allowDuplicate !== 'boolean') invalid('allowDuplicate no es válido'); const data = validateTaskFields(taskArguments, { titleRequired: true }); if (!allowDuplicate) { const existingTask = await database.findDuplicateTask(data); if (existingTask) return { ok: false, reason: 'duplicate', existingTask: { id: existingTask.id, title: existingTask.title, date: existingTask.date, time: existingTask.time }, dataChanged: false }; } return { ok: true, data: await database.createTask(data), dataChanged: true }; }
    if (name === 'buscar_tareas') { if (!args || typeof args !== 'object' || Array.isArray(args)) invalid('argumentos no válidos'); assertKeys(args, ['texto', 'fecha', 'completada', 'etiqueta', 'prioridad', 'personaId']); const filters = {}; if (Object.prototype.hasOwnProperty.call(args, 'texto')) filters.text = stringValue(args.texto, 'texto', MAX_TEXT_LENGTH); if (Object.prototype.hasOwnProperty.call(args, 'fecha')) filters.date = validateDate(args.fecha, 'fecha'); if (Object.prototype.hasOwnProperty.call(args, 'completada')) { if (typeof args.completada !== 'boolean') invalid('completada no es válida'); filters.completed = args.completada; } if (Object.prototype.hasOwnProperty.call(args, 'etiqueta')) filters.tag = stringValue(args.etiqueta, 'etiqueta', MAX_TAG_LENGTH, true).replace(/^#?/, '#'); if (Object.prototype.hasOwnProperty.call(args, 'prioridad')) { if (!priorities.includes(args.prioridad)) invalid('prioridad no es válida'); filters.priority = args.prioridad; } if (Object.prototype.hasOwnProperty.call(args, 'personaId')) filters.personId = validateId(args.personaId); return { ok: true, data: await database.searchTasks(filters), dataChanged: false }; }
    if (name === 'consultar_alertas') { assertKeys(args || {}, []); return { ok: true, data: await advisor.analyze(), dataChanged: false }; }
    if (name === 'crear_recordatorio') { if (!args || typeof args !== 'object' || Array.isArray(args)) invalid('argumentos no válidos'); assertKeys(args, ['taskId', 'dateTime', 'type']); const taskId = validateId(args.taskId); if (!(await database.findTask(taskId))) return { ok: false, error: 'Tarea no encontrada', dataChanged: false }; const dateTime = parseReminderDateTime(stringValue(args.dateTime, 'dateTime', 16, true)); const existing = await database.findDuplicateReminder(taskId, dateTime); if (existing) return { ok: false, reason: 'duplicate', data: existing, dataChanged: false }; return { ok: true, data: await database.createReminder({ taskId, dateTime, type: stringValue(args.type, 'type', 40) || 'notification' }), dataChanged: true }; }
    if (name === 'crear_recordatorio_relativo') { if (!args || typeof args !== 'object' || Array.isArray(args)) invalid('argumentos no válidos'); assertKeys(args, ['taskId', 'advance', 'type']); const taskId = validateId(args.taskId); const task = await database.findTask(taskId); if (!task) return { ok: false, error: 'Tarea no encontrada', dataChanged: false }; let dateTime; try { dateTime = time.localDateTimeFromTaskAdvance(task, args.advance).toISOString(); } catch (error) { invalid(error.message); } const existing = await database.findDuplicateReminder(taskId, dateTime); if (existing) return { ok: false, reason: 'duplicate', data: existing, dataChanged: false }; return { ok: true, data: await database.createReminder({ taskId, dateTime, type: stringValue(args.type, 'type', 40) || 'notification' }), dataChanged: true }; }
    if (name === 'buscar_recordatorios') { if (!args || typeof args !== 'object' || Array.isArray(args)) invalid('argumentos no válidos'); assertKeys(args, ['taskId', 'pending', 'date', 'sent']); const filters = {}; if (Object.prototype.hasOwnProperty.call(args, 'taskId')) filters.taskId = validateId(args.taskId); if (Object.prototype.hasOwnProperty.call(args, 'sent')) { if (typeof args.sent !== 'boolean') invalid('sent no es válido'); filters.sent = args.sent; } if (Object.prototype.hasOwnProperty.call(args, 'pending')) { if (typeof args.pending !== 'boolean') invalid('pending no es válido'); filters.sent = !args.pending; } if (Object.prototype.hasOwnProperty.call(args, 'date')) filters.date = stringValue(args.date, 'date', 10); return { ok: true, data: await database.findReminders(filters), dataChanged: false }; }
    if (name === 'editar_recordatorio') { const id = validateId(args?.id); const data = {}; if (Object.prototype.hasOwnProperty.call(args, 'dateTime')) data.dateTime = parseReminderDateTime(stringValue(args.dateTime, 'dateTime', 16, true)); if (Object.prototype.hasOwnProperty.call(args, 'sent')) { if (typeof args.sent !== 'boolean') invalid('sent no es válido'); data.sent = args.sent; } if (Object.prototype.hasOwnProperty.call(args, 'type')) data.type = stringValue(args.type, 'type', 40); const updated = await database.updateReminderPartial(id, data); return updated ? { ok: true, data: updated, dataChanged: Object.keys(data).length > 0 } : { ok: false, error: 'Recordatorio no encontrado', dataChanged: false }; }
    if (name === 'eliminar_recordatorio') { const id = validateId(args?.id); const result = await database.deleteReminder(id); return result.changes ? { ok: true, dataChanged: true } : { ok: false, error: 'Recordatorio no encontrado', dataChanged: false }; }
    if (name === 'posponer_recordatorio') { const id = validateId(args?.id); if (!Number.isInteger(args?.minutes) || args.minutes < 1 || args.minutes > 10080) invalid('minutes no es válido'); const existing = await database.findReminder(id); if (!existing) return { ok: false, error: 'Recordatorio no encontrado', dataChanged: false }; const dateTime = time.addMinutes(new Date(existing.dateTime), args.minutes).toISOString(); return { ok: true, data: await database.updateReminderPartial(id, { dateTime, sent: false }), dataChanged: true }; }
    if (name === 'buscar_etiquetas') { if (!args || typeof args !== 'object' || Array.isArray(args)) invalid('argumentos no válidos'); assertKeys(args, ['texto']); return { ok: true, data: await database.searchTags(stringValue(args.texto, 'texto', MAX_TAG_LENGTH)), dataChanged: false }; }
    if (name === 'editar_tarea') { const id = validateId(args?.id); const data = validateTaskFields(args); if (!Object.keys(data).length) invalid('debes indicar un campo para editar'); const updated = await database.updateTaskPartial(id, data); return updated ? { ok: true, data: updated, dataChanged: true } : { ok: false, error: 'Tarea no encontrada', dataChanged: false }; }
    if (name === 'completar_tarea') { const id = validateId(args?.id); const task = await database.findTask(id); if (!task) return { ok: false, error: 'Tarea no encontrada', dataChanged: false }; return { ok: true, data: await database.updateTaskPartial(id, { completed: true }), dataChanged: true }; }
    if (name === 'eliminar_tarea') { const id = validateId(args?.id); const task = await database.findTask(id); if (!task) return { ok: false, error: 'Tarea no encontrada', dataChanged: false }; const result = await database.deleteTask(id); return result.changes ? { ok: true, data: { id, title: task.title }, dataChanged: true } : { ok: false, error: 'No se pudo eliminar la tarea', dataChanged: false }; }
    if (name === 'buscar_personas') { if (!args || typeof args !== 'object' || Array.isArray(args)) invalid('argumentos no válidos'); assertKeys(args, ['nombre', 'apodo', 'relacion', 'organizacion', 'telefono', 'correo']); return { ok: true, data: await database.searchPeople({ name: stringValue(args.nombre, 'nombre', MAX_PERSON_FIELD_LENGTH), nickname: stringValue(args.apodo, 'apodo', MAX_PERSON_FIELD_LENGTH), relationship: stringValue(args.relacion, 'relacion', MAX_PERSON_FIELD_LENGTH), organization: stringValue(args.organizacion, 'organizacion', MAX_PERSON_FIELD_LENGTH), phone: stringValue(args.telefono, 'telefono', MAX_PHONE_LENGTH), email: stringValue(args.correo, 'correo', MAX_EMAIL_LENGTH) }), dataChanged: false }; }
    if (name === 'crear_persona') { const data = validatePersonFields(args, { fullNameRequired: true }); const existing = await database.findPersonByNormalizedName(data.fullName); if (existing) return { ok: false, reason: 'duplicate', person: existing, dataChanged: false }; return { ok: true, data: await database.createPerson(data), dataChanged: true }; }
    if (name === 'editar_persona') { const id = validateId(args?.id); const data = validatePersonFields(args); const updated = await database.updatePersonPartial(id, data); return updated ? { ok: true, data: updated, dataChanged: Object.keys(data).length > 0 } : { ok: false, error: 'Persona no encontrada', dataChanged: false }; }
    invalid('herramienta no permitida');
  } catch (error) { if (error.publicMessage) return { ok: false, error: error.publicMessage, dataChanged: false }; return { ok: false, error: 'No se pudo completar la operación.', dataChanged: false }; }
}

module.exports = { tools, execute };
